const int TOTAL_ROOMS = 12;
const int TOTAL_DIRS = 4;
const int TOTAL_VERBS = 20;
const int TOTAL_NOUNS = 16;
enum Directions { NORTH, SOUTH, EAST, WEST };
enum Verbs {
    QUIT, LOOK, INV, GO, HELP, OPEN, CLOSE, GET, DROP, WHERE,
    CUT, CLEAN, WATCH, RUN, WALK, WAIT, EAT, SEARCH, JUMP, STAB
};
enum Nouns {
    RASP_PIE, BLUE_PIE, BAKERY_FRONT_DOOR, KNIFE, FLOUR, BAKERY_BACK_DOOR,
    DUMPSTER, POISON, FENCE,
    SECURITY_CAM, CAR, ASPHALT, MOON,
    WASH_MACHINE, DRYER, LAUNDROMAT_DOOR
};
enum Rooms {
    POCKET, ENTRYPOINT,
    TERRIBLE_END, BAD_END, NEUTRAL_END, GOOD_END, BEST_END,
    BAKERY_FRONT, BAKERY_BACK, BAKERY_BEHIND,
    OUTSIDE_0,
    LAUNDROMAT,
};
